--liquibase formatted.sql
--changeset michael.cawayan:MONITOR.RTDM_LOG_IF144_SMOKE_TEST contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
  CREATE TABLE "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" (
 LOG_SMOKETEST_ID	NUMBER
,CORRELATION_ID	VARCHAR2(100)
,ID_CUID	NUMBER
,CHANNEL_CD	VARCHAR2(10)
,CREATED_DTTM	TIMESTAMP(6)
,UPDATED_DTTM	TIMESTAMP(6)
,RTDM_HOSTNAME	VARCHAR2(50)
,STATUS	VARCHAR2(15)
,STATUS_DESCRIPTION	VARCHAR2(1024)
,IL_COMMUNICATION_ID	NUMBER
,CH_ID	NUMBER  
,CONSTRAINT "RTDM_LOG_IF144_SMOKE_TEST_PK" PRIMARY KEY ("LOG_SMOKETEST_ID") USING INDEX  ENABLE)  
PARTITION BY RANGE ("CREATED_DTTM") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))  
(PARTITION "PINIT"  VALUES LESS THAN (TIMESTAMP' 2025-12-01 00:00:00') 
)  ENABLE ROW MOVEMENT 
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE INDEX "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST_IDX1" ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" ("CORRELATION_ID") 
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE INDEX "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST_IDX2" ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" ("ID_CUID")
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT DELETE ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" TO "MA_TEMP"
/
GRANT INSERT ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" TO "MA_TEMP"
/
GRANT SELECT ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" TO "MA_TEMP"
/
GRANT UPDATE ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" TO "MA_TEMP"
/
GRANT DELETE ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" TO "ESP_USER"
/
GRANT INSERT ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" TO "ESP_USER"
/
GRANT SELECT ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" TO "ESP_USER"
/
GRANT UPDATE ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" TO "ESP_USER"
/
GRANT SELECT ON "MONITOR"."RTDM_LOG_IF144_SMOKE_TEST" TO "HCI_RO_MONITOR"
/