--liquibase formatted.sql
--changeset michael.cawayan:MONITOR.RTDM_LOG_IF143_REL contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE MONITOR.RTDM_LOG_IF143_REL
(
 REL_LOG_ID	NUMBER
,CORRELATION_ID	VARCHAR2(100 CHAR)
,ACCOUNT_STATUS	VARCHAR2(20 CHAR)
,ACCOUNT_TYPE	VARCHAR2(100 CHAR)
,ACCOUNT_NUMBER	NUMBER
,EVENT_TIMESTAMP	TIMESTAMP(6)
,EVENT_NAME	VARCHAR2(100 CHAR)
,EVENT_TYPE_ENUM	VARCHAR2(50 CHAR)
,TXN_SOURCEID_SOURCE_SYSTEM	VARCHAR2(50 CHAR)
,TXN_SOURCEID_SOURCE_TXID	VARCHAR2(50 CHAR)
,TRUNCATED_PAN	VARCHAR2(50 CHAR)
,AUTH_AUTHORIZATION_MODE	VARCHAR2(50 CHAR)
,AUTH_CU_MCC	VARCHAR2(50 CHAR)
,AUTH_CU_CA_CITY	VARCHAR2(50 CHAR)
,AUTH_CU_CA_COUNTRY_CODE	VARCHAR2(20 CHAR)
,AUTH_CU_CA_NAME	VARCHAR2(100 CHAR)
,AUTH_BILLING_AMOUNT_VALUE	NUMBER
,AUTH_TXN_AMOUNT_VALUE	NUMBER
,AUTH_TXN_AMOUNT_CURRENCY	VARCHAR2(20 CHAR)
,AUTH_TYPE	VARCHAR2(20 CHAR)
,CUID	NUMBER
,CREATED_DTTM	TIMESTAMP(6)
,UPDATED_DTTM	TIMESTAMP(6)
,RTDM_HOSTNAME	VARCHAR2(50 CHAR)
,LOG_SOURCE	VARCHAR2(10 CHAR)
,STATUS	VARCHAR2(15 CHAR)
,STATUS_DESCRIPTION	VARCHAR2(1024 CHAR)
,CHANNEL_CD	VARCHAR2(10 CHAR)
,IL_COMMUNICATION_ID	NUMBER
,CH_ID	NUMBER
,BUS_RTDM_EVENT_ID	VARCHAR2(100 CHAR)
,CONSTRAINT "RTDM_LOG_IF143_REL_PK" PRIMARY KEY ("REL_LOG_ID") USING INDEX  ENABLE)  
PARTITION BY RANGE ("CREATED_DTTM") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))  
(PARTITION "PINIT"  VALUES LESS THAN (TIMESTAMP' 2025-12-01 00:00:00') 
)  ENABLE ROW MOVEMENT 
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE INDEX "MONITOR"."RTDM_LOG_IF143_REL_IDX1" ON "MONITOR"."RTDM_LOG_IF143_REL" ("CORRELATION_ID")
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE INDEX "MONITOR"."RTDM_LOG_IF143_REL_IDX2" ON "MONITOR"."RTDM_LOG_IF143_REL" ("ACCOUNT_NUMBER")
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT DELETE ON "MONITOR"."RTDM_LOG_IF143_REL" TO "MA_TEMP"
/
GRANT INSERT ON "MONITOR"."RTDM_LOG_IF143_REL" TO "MA_TEMP"
/
GRANT SELECT ON "MONITOR"."RTDM_LOG_IF143_REL" TO "MA_TEMP"
/
GRANT UPDATE ON "MONITOR"."RTDM_LOG_IF143_REL" TO "MA_TEMP"
/
GRANT DELETE ON "MONITOR"."RTDM_LOG_IF143_REL" TO "ESP_USER"
/
GRANT INSERT ON "MONITOR"."RTDM_LOG_IF143_REL" TO "ESP_USER"
/
GRANT SELECT ON "MONITOR"."RTDM_LOG_IF143_REL" TO "ESP_USER"
/
GRANT UPDATE ON "MONITOR"."RTDM_LOG_IF143_REL" TO "ESP_USER"
/
GRANT SELECT ON "MONITOR"."RTDM_LOG_IF143_REL" TO "HCI_RO_MONITOR"
/
