--liquibase formatted.sql
--changeset michael.cawayan:MONITOR.V_GET_LOG_IF144_ID contextFilter:PH endDelimiter:/ runOnChange:true

CREATE OR REPLACE EDITIONABLE VIEW "MONITOR"."V_GET_LOG_IF144_ID" ("LOG_SMOKETEST_ID") AS 
select MONITOR.GET_IF144_ID from DUAL
/
GRANT SELECT ON "MONITOR"."V_GET_LOG_IF144_ID" TO "MA_TEMP"
/
GRANT SELECT ON "MONITOR"."V_GET_LOG_IF144_ID" TO "HCI_RO_MONITOR"
/
GRANT SELECT ON "MONITOR"."V_GET_LOG_IF144_ID" TO "HCI_APP_SELECT"
/
GRANT SELECT ON "MONITOR"."V_GET_LOG_IF144_ID" TO "APPSUPPORT"
/